server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: hcw-zuul
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
zuul:
  routes:
    sys:
      serviceId: hcw-sys-web
      path: /sys/**
  prefix: /hcw
